version: '3.8'

services:
  db:
    image: mongo:5.0
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      MONGODB_URL: "mongodb://db:27017"

volumes:
  mongodb_data:
