services:
  mongo:
    image: mongo:8.0.5
    ports:
      - 27017:27017

  backend:
    depends_on:
      - mongo
    image: backend:test
    build: ./backend
    ports:
      - 8000:8000

  frontend:
    depends_on:
      - backend
    image: frontend:test
    build: ./frontend
    ports:
      - 5173:80